anatomicalTemplate  :  /home/alexandre/Data/cobre/raw/%s/session_1/anat_1/mprage.nii.gz

functionalTemplate  :  /home/alexandre/Data/cobre/raw/%s/session_1/rest_1/rest.nii.gz

subjectList  :  None

exclusionSubjectList  :  None

siteList  :  None

scanParametersCSV  :  None

outputSubjectListLocation  :  None

subjectListName  :  ['COBRE']
