anatomicalTemplate  :  /home/alexandre/Data/cobre/raw/%s/%s/anat_1/mprage.nii.gz

functionalTemplate  :  /home/alexandre/Data/cobre/raw/%s/%s/rest_1/rest.nii.gz

subjectList  :  None

exclusionSubjectList  :  None

siteList  :  None

scanParametersCSV  :  None

outputSubjectListLocation  :  None

subjectListName  :  ['COBRE']
